from .constants import (
    GPT4_MODEL,
    GEMINI_MODEL,
    PDF_MIME_TYPE,
    DOCX_MIME_TYPE,
    HIGH_SCORE_THRESHOLD,
    MEDIUM_SCORE_THRESHOLD,
    HIGH_SCORE_COLOR,
    MEDIUM_SCORE_COLOR,
    LOW_SCORE_COLOR,
    USER_AGENT
)
from .config import config

__all__ = [
    'config',
    'GPT4_MODEL',
    'GEMINI_MODEL',
    'PDF_MIME_TYPE',
    'DOCX_MIME_TYPE',
    'HIGH_SCORE_THRESHOLD',
    'MEDIUM_SCORE_THRESHOLD',
    'HIGH_SCORE_COLOR',
    'MEDIUM_SCORE_COLOR',
    'LOW_SCORE_COLOR',
    'USER_AGENT'
]
